# Generated by Django 4.1.3 on 2022-11-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cHacksApp', '0002_alter_user_rank_alter_user_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
